version: "3.8"
services:
    app:
        build: .
        ports:
            - "5000:5000"
        environment:
            - SQLALCHEMY_DATABASE_URI=mysql://root:password@db/library
            - SQLALCHEMY_TRACK_MODIFICATIONS=0
            - FLASK_ENV=development
        depends_on:
            - db
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=library